import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen`}
      >
        <header className="bg-white border-b border-gray-200 shadow-sm sticky top-0 z-10">
          <nav className="max-w-4xl mx-auto px-6 py-4 flex justify-between items-center">
            <div className="text-xl font-bold text-blue-900 flex items-center gap-2">
              <span className="bg-blue-600 text-white p-1 rounded">📦</span>
              Logística Express
            </div>
            <div className="flex gap-6">
              <a href="/" className="text-gray-600 hover:text-blue-600 font-medium transition-colors">Rastrear</a>
              <a href="/create" className="text-gray-600 hover:text-blue-600 font-medium transition-colors">Cadastrar Pacote</a>
            </div>
          </nav>
        </header>
        <div className="py-8">
          {children}
        </div>
      </body>
    </html>
  );
}
